spring:
  datasource:
    url: "jdbc:mysql://10.100.3.12:3306/qrbgw?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&tinyInt1isBit=false"
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  profile:
    include:
      - unionpay
      - gateway