package com.qrroad.oqms.domain.dto;

import lombok.Builder;
import lombok.Getter;
import java.math.BigDecimal;
import java.sql.Timestamp;

@Getter
@Builder
public class OqPaymentDto {
    private final String trxDt;
    private final String trxTm;
    private final String txnId;
    private final String instCd;
    private final String spayCoCd;
    private final String trxCl;
    private final String trxIn;
    private final String token;
    private final String deviceId;
    private final String srcDigitalCardId;
    private final BigDecimal trxAmt;
    private final String trxCurrency;
    private final BigDecimal originalAmount;
    private final BigDecimal trxFeeAmt;
    private final String qrPayload;
    private final String barcodeCpQrcPayload;
    private final String srcCorrelationId;
    private final String qrcVoucherNo;
    private final String couponInfo;
    private final String retrievalReferenceNumber;
    private final String merchantId;
    private final String merchantName;
    private final String mcc;
    private final String subMerchantName;
    private final String subMerchantId;
    private final BigDecimal cdhldrBillAmt;
    private final String cdhldrBillCurrency;
    private final BigDecimal cdhldrBillConvRate;
    private final String acquirerIin;
    private final String forwardingIin;
    private final String systemTraceAuditNumber;
    private final String transmissionDateTime;
    private final String gps;
    private final String simcard;
    private final String appUserId;
    private final String usrEnrolDate;
    private final String captureMethod;
    private final String ipAddress;
    private final String reservedMobileNo;
    private final String deviceType;
    private final String deviceScore;
    private final String billNo;
    private final String mobileNo;
    private final String storeLabel;
    private final String loyaltyNumber;
    private final String referenceLabel;
    private final String customerLabel;
    private final String terminalLabel;
    private final String trxPurpose;
    private final String consumerEmail;
    private final String consumerAddress;
    private final BigDecimal discountAmt1;
    private final String discountNote1;
    private final BigDecimal discountAmt2;
    private final String discountNote2;
    private final BigDecimal discountAmt3;
    private final String discountNote3;
    private final BigDecimal discountAmt4;
    private final String discountNote4;
    private final BigDecimal discountAmt5;
    private final String discountNote5;
    private final String paymentStatus;
    private final String rejectionReason;
    private final String responseCode;
    private final String responseMsg;
    private final String payOrderInfo;
    private final String msgId;
    private final String walletId;
    private final Timestamp updateTime;
    private final Timestamp createTime;
}
